### ISSUE TITLE
Terjemahkan ke bahasa inggris

### ISSUE THREAD

**Issue by mnirfan** [DOSCOM/tealinuxos.org#38]
buat kamu yang pengen ikut hacktoberfest bisa kontrib ke sini. menerjemahkan bahasa indonesia ke bahasa inggris. file ada di `/src/en/panduan`. Selamat berjuang :)

**Comment by hariesramdhani** [comment]
Hi bisa saya bantu untuk ini? :)

**Comment by captainjex** [comment]
Sangat bisa :D file ada di directory `/src/en/panduan`. Silakan edit di bagian title dan isinya. Untuk `type` dan `order` bisa dibiarkan saja. 

![image](https://user-images.githubusercontent.com/21119252/31116522-9cc3587e-a850-11e7-8329-fff669ed04ad.png)

**Comment by hariesramdhani** [comment]
Ok sip, working on it

**Comment by ruzfi** [comment]
isunya sudah selesai kan ?. make as clossed Min 😄
