### ISSUE TITLE
Image Upload - migrasi ke hexo

### ISSUE THREAD

**Issue by captainjex** [DOSCOM/tealinuxos.org#8]
tempat upload gambar

**Comment by niyayeah** [comment]
![menu](https://cloud.githubusercontent.com/assets/26142091/23577576/a90a1a1c-00f5-11e7-86ec-d4bc4d831a13.png)

**Comment by niyayeah** [comment]
![panel](https://cloud.githubusercontent.com/assets/26142091/23577600/74a27d68-00f6-11e7-8b00-8dc2094948d1.png)

**Comment by niyayeah** [comment]
![dekstop](https://cloud.githubusercontent.com/assets/26142091/23577631/e41eff86-00f6-11e7-8359-c21b5e649e5d.png)

**Comment by niyayeah** [comment]
![filemanager](https://cloud.githubusercontent.com/assets/26142091/23577653/6320e772-00f7-11e7-8b8e-d3e54d198839.png)

**Comment by niyayeah** [comment]
![theme-switcher](https://cloud.githubusercontent.com/assets/26142091/23577696/a5647cc4-00f8-11e7-84eb-13bdef4a8464.png)

**Comment by niyayeah** [comment]
![multimedia](https://cloud.githubusercontent.com/assets/26142091/23577778/c11fde0c-00fa-11e7-8244-ec175efb3fde.png)

**Comment by niyayeah** [comment]
![teapackage](https://cloud.githubusercontent.com/assets/26142091/23577786/f179e818-00fa-11e7-8a7c-8fd3756e9ed8.png)

**Comment by niyayeah** [comment]
![moduleinstaller](https://cloud.githubusercontent.com/assets/26142091/23577794/155d48ba-00fb-11e7-999b-fdd614960e12.png)

**Comment by niyayeah** [comment]
![lapor-hama](https://cloud.githubusercontent.com/assets/26142091/23577802/442cbd2e-00fb-11e7-9f24-b2295cf0cbac.png)

**Comment by niyayeah** [comment]
![networkmanager](https://cloud.githubusercontent.com/assets/26142091/23577859/8c296144-00fc-11e7-9884-b770de64ba36.png)

**Comment by ciazhar** [comment]
![1 bootable](https://cloud.githubusercontent.com/assets/22718275/23578142/c4eae682-0102-11e7-9d76-69cd286a4406.png)

**Comment by ciazhar** [comment]
![2 bootable](https://cloud.githubusercontent.com/assets/22718275/23578146/d6ebc932-0102-11e7-94c9-993dee8bcbe2.png)

**Comment by ciazhar** [comment]
![3 partition](https://cloud.githubusercontent.com/assets/22718275/23578147/e2c49112-0102-11e7-868e-611db63be0a2.png)

**Comment by ciazhar** [comment]
![4 partition](https://cloud.githubusercontent.com/assets/22718275/23578150/f11bd6d0-0102-11e7-815c-b4648866def9.png)

**Comment by ciazhar** [comment]
![5 language](https://cloud.githubusercontent.com/assets/22718275/23578153/0b7894f0-0103-11e7-80ff-867f2cd9bd6b.jpg)

**Comment by ciazhar** [comment]
![6 preparing](https://cloud.githubusercontent.com/assets/22718275/23578155/1bdc071e-0103-11e7-9764-54656d453f0a.jpg)

**Comment by ciazhar** [comment]
![7 installing type](https://cloud.githubusercontent.com/assets/22718275/23578160/30357e66-0103-11e7-87ed-b91224a339e2.jpg)

**Comment by ciazhar** [comment]
![8 partition](https://cloud.githubusercontent.com/assets/22718275/23578165/43c978ec-0103-11e7-8350-da7bfa07ff88.jpg)

**Comment by ciazhar** [comment]
![9 partition](https://cloud.githubusercontent.com/assets/22718275/23578171/5c5b24b4-0103-11e7-9506-90487dd24a5a.jpg)

**Comment by ciazhar** [comment]
![10 ext4_1](https://cloud.githubusercontent.com/assets/22718275/23578177/6d0f681a-0103-11e7-9cf4-c2ece29fa1e5.jpg)

**Comment by niyayeah** [comment]
![software-center](https://cloud.githubusercontent.com/assets/26142091/23578129/6d894e06-0102-11e7-8672-2a7212299881.png)

**Comment by ciazhar** [comment]
![1_menu-install](https://cloud.githubusercontent.com/assets/22718275/23685947/5be6f430-03d9-11e7-89c0-d55cfb593f9e.png)

**Comment by ciazhar** [comment]
![2_try install](https://cloud.githubusercontent.com/assets/22718275/23685964/736151be-03d9-11e7-9b11-23af4063ab3b.png)

**Comment by ciazhar** [comment]
![3_language](https://cloud.githubusercontent.com/assets/22718275/23685974/7fc2ecf6-03d9-11e7-8a1f-c5b31b94c6e0.png)

**Comment by ciazhar** [comment]
![3_language](https://cloud.githubusercontent.com/assets/22718275/23685988/96e996fa-03d9-11e7-9cc0-b5664ed27a17.png)

**Comment by ciazhar** [comment]
![4_preparing](https://cloud.githubusercontent.com/assets/22718275/23685998/a811ae18-03d9-11e7-8c6f-1900f9a85b7d.png)

**Comment by ciazhar** [comment]
![5_installation](https://cloud.githubusercontent.com/assets/22718275/23686028/cd308aac-03d9-11e7-9fa7-217fd1f7ac08.png)

**Comment by ciazhar** [comment]
![6_partition_1](https://cloud.githubusercontent.com/assets/22718275/23686041/e39d8f38-03d9-11e7-8836-e749fb8b0794.png)

**Comment by ciazhar** [comment]
![7_partition_2](https://cloud.githubusercontent.com/assets/22718275/23686049/f5030230-03d9-11e7-8834-7ecac4b9b6bb.png)

**Comment by ciazhar** [comment]
![8_partition_3](https://cloud.githubusercontent.com/assets/22718275/23686061/03f969f0-03da-11e7-8bda-eb56c7c8cf04.png)

**Comment by ciazhar** [comment]
![9_partition_4](https://cloud.githubusercontent.com/assets/22718275/23686081/1fbf6266-03da-11e7-8daa-4a60c06703e5.png)

**Comment by ciazhar** [comment]
![10_partition_5](https://cloud.githubusercontent.com/assets/22718275/23686146/6dbf052a-03da-11e7-85e3-e844b273f694.png)

**Comment by ciazhar** [comment]
![11_partition_6](https://cloud.githubusercontent.com/assets/22718275/23686161/857a51e2-03da-11e7-8011-a9fb063761b4.png)

**Comment by ciazhar** [comment]
![12_time-and-region](https://cloud.githubusercontent.com/assets/22718275/23686187/a58ca03e-03da-11e7-827a-01f86abe8ec3.png)

**Comment by ciazhar** [comment]
![13_keyboard-layout](https://cloud.githubusercontent.com/assets/22718275/23686208/b682f4ce-03da-11e7-8dcb-85c8ef2cbbad.png)

**Comment by ciazhar** [comment]
![14_whoru](https://cloud.githubusercontent.com/assets/22718275/23686238/d5fdd5e4-03da-11e7-8387-626587c4ede8.png)

**Comment by ciazhar** [comment]
![15_installation](https://cloud.githubusercontent.com/assets/22718275/23686286/31ab73ec-03db-11e7-8292-173401c6851a.png)

**Comment by ciazhar** [comment]
![17_success](https://cloud.githubusercontent.com/assets/22718275/23686381/df3fda20-03db-11e7-9ee1-a811f1646f36.png)
